theme: jekyll-theme-minimal
title: Rablashijupa Website
description: Website for our ADA project
show_downloads: True
navigation:
  - title: Home
    url: p3_step4
  - title: Example
    url: example

